2024-05-10 11:28:17 - src.logs.config_logger - INFO - Iniciando instalador
2024-05-10 11:28:17 - src.logs.config_logger - INFO - Creando archivo 'Presupuestador.bat'
2024-05-10 11:28:17 - src.logs.config_logger - INFO - Archivo 'Presupuestador.bat' creado exitosamente.
2024-05-10 11:28:17 - src.logs.config_logger - INFO - Acceso directo actualizado exitosamente.
2024-05-10 11:30:02 - src.logs.config_logger - INFO - Iniciando instalador
2024-05-10 11:30:02 - src.logs.config_logger - INFO - Acceso directo actualizado exitosamente.
2024-05-10 11:36:23 - src.logs.config_logger - INFO - Iniciando instalador
2024-05-10 11:36:23 - src.logs.config_logger - INFO - Acceso directo actualizado exitosamente.
2024-05-10 11:37:44 - src.logs.config_logger - INFO - Iniciando instalador
2024-05-10 11:37:44 - src.logs.config_logger - INFO - Creando archivo 'Presupuestador.bat'
2024-05-10 11:37:44 - src.logs.config_logger - INFO - Archivo 'Presupuestador.bat' creado exitosamente.
2024-05-10 11:37:44 - src.logs.config_logger - INFO - Acceso directo actualizado exitosamente.
2024-05-10 11:48:31 - src.logs.config_logger - INFO - Iniciando instalador
2024-05-10 11:48:31 - src.logs.config_logger - INFO - Creando archivo 'Presupuestador.bat'
2024-05-10 11:48:31 - src.logs.config_logger - INFO - Archivo 'Presupuestador.bat' creado exitosamente.
2024-05-10 11:48:31 - src.logs.config_logger - INFO - Acceso directo actualizado exitosamente.
2024-05-10 11:51:10 - src.logs.config_logger - INFO - Iniciando instalador
2024-05-10 11:51:10 - src.logs.config_logger - INFO - Acceso directo actualizado exitosamente.
2024-05-10 11:59:04 - logs.config_logger - INFO - Iniciando la aplicación
2024-05-10 11:59:04 - logs.config_logger - INFO - Conexión inicial sin base de datos establecida exitosamente.
2024-05-10 11:59:04 - logs.config_logger - INFO - Base de datos 'presupuestador_db' creada exitosamente.
2024-05-10 11:59:04 - logs.config_logger - DEBUG - Creando tablas en la base de datos
2024-05-10 11:59:04 - logs.config_logger - INFO - Tabla 'presupuestos' creada exitosamente.
2024-05-10 11:59:04 - logs.config_logger - INFO - Tabla 'vendedores' creada exitosamente.
2024-05-10 11:59:04 - logs.config_logger - INFO - Tabla 'clientes' creada exitosamente.
2024-05-10 11:59:04 - logs.config_logger - INFO - Tabla 'items' creada exitosamente.
2024-05-10 11:59:04 - logs.config_logger - INFO - Reconectado a la nueva base de datos 'presupuestador_db'.
2024-05-10 11:59:04 - logs.config_logger - DEBUG - Creando tablas en la base de datos
2024-05-10 11:59:04 - logs.config_logger - INFO - Tabla 'presupuestos' creada exitosamente.
2024-05-10 11:59:04 - logs.config_logger - INFO - Tabla 'vendedores' creada exitosamente.
2024-05-10 11:59:04 - logs.config_logger - INFO - Tabla 'clientes' creada exitosamente.
2024-05-10 11:59:04 - logs.config_logger - INFO - Tabla 'items' creada exitosamente.
2024-05-10 11:59:18 - logs.config_logger - INFO - Modo TEST activado: Generando PDF vacío.
2024-05-10 11:59:18 - logs.config_logger - DEBUG - Ruta del archivo configurada: C:\AppServ\www\Presupuestador\generated_pdfs\test_20240510_115918.pdf
2024-05-10 11:59:18 - logs.config_logger - INFO - PDF generado exitosamente.
2024-05-10 11:59:26 - logs.config_logger - INFO - Modo TEST activado: Generando PDF vacío.
2024-05-10 11:59:26 - logs.config_logger - DEBUG - Ruta del archivo configurada: C:\AppServ\www\Presupuestador\generated_pdfs\test_20240510_115926.pdf
2024-05-10 11:59:26 - logs.config_logger - INFO - PDF generado exitosamente.
2024-05-10 12:01:25 - logs.config_logger - INFO - Iniciando la aplicación
2024-05-10 12:01:25 - logs.config_logger - INFO - Conectado al servidor MySQL versión 8.0.17
2024-05-10 12:01:49 - logs.config_logger - INFO - Modo TEST activado: Generando PDF vacío.
2024-05-10 12:01:49 - logs.config_logger - DEBUG - Ruta del archivo configurada: C:\AppServ\www\Presupuestador\generated_pdfs\test_20240510_120149.pdf
2024-05-10 12:01:49 - logs.config_logger - INFO - PDF generado exitosamente.
2024-05-10 13:27:57 - logs.config_logger - INFO - Iniciando la aplicación
2024-05-10 13:27:57 - logs.config_logger - INFO - Conectado al servidor MySQL versión 8.0.17
2024-05-10 13:28:00 - logs.config_logger - INFO - Modo TEST activado: Generando PDF vacío.
2024-05-10 13:28:00 - logs.config_logger - DEBUG - Ruta del archivo configurada: C:\AppServ\www\Presupuestador\generated_pdfs\test_20240510_132800.pdf
2024-05-10 13:28:00 - logs.config_logger - INFO - PDF generado exitosamente.
2024-05-10 13:31:16 - logs.config_logger - INFO - Iniciando la aplicación
2024-05-10 13:31:16 - logs.config_logger - INFO - Conectado al servidor MySQL versión 8.0.17
2024-05-10 13:31:23 - logs.config_logger - INFO - Modo TEST activado: Generando PDF vacío.
2024-05-10 13:31:23 - logs.config_logger - DEBUG - Ruta del archivo configurada: C:\AppServ\www\Presupuestador\generated_pdfs\test_20240510_133123.pdf
2024-05-10 13:31:23 - logs.config_logger - INFO - PDF generado exitosamente.
2024-05-16 10:19:43 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 10:19:43 - logs.config_logger - ERROR - database.py:46 - Error de programación en SQL: 1049 (42000): Unknown database 'presupuestador_db'
2024-05-16 10:19:43 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 10:21:58 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 10:21:58 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 10:21:58 - logs.config_logger - INFO - database.py:92 - No se encontraron tablas en la base de datos. Creando tablas...
2024-05-16 10:21:58 - logs.config_logger - DEBUG - database.py:99 - Creando tablas en la base de datos
2024-05-16 10:21:58 - logs.config_logger - INFO - database.py:118 - Tabla 'presupuestos' creada exitosamente.
2024-05-16 10:21:58 - logs.config_logger - INFO - database.py:129 - Tabla 'vendedores' creada exitosamente.
2024-05-16 10:21:58 - logs.config_logger - INFO - database.py:147 - Tabla 'clientes' creada exitosamente.
2024-05-16 10:21:58 - logs.config_logger - INFO - database.py:160 - Tabla 'items' creada exitosamente.
2024-05-16 10:22:03 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 10:24:02 - logs.config_logger - DEBUG - pdf_generator.py:152 - Ruta del archivo configurada: C:\AppServ\www\Presupuestador\generated_pdfs\presupuesto_N1_20240516_102402.pdf
2024-05-16 10:24:02 - logs.config_logger - INFO - pdf_generator.py:155 - PDF generado exitosamente.
2024-05-16 10:45:58 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 10:45:58 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 10:46:28 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 10:46:28 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 10:46:56 - logs.config_logger - INFO - pdf_generator.py:169 - Modo TEST activado: Generando PDF vacío.
2024-05-16 10:46:56 - logs.config_logger - DEBUG - pdf_generator.py:152 - Ruta del archivo configurada: C:\AppServ\www\Presupuestador\generated_pdfs\test_20240516_104656.pdf
2024-05-16 10:46:56 - logs.config_logger - INFO - pdf_generator.py:155 - PDF generado exitosamente.
2024-05-16 10:54:36 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 10:54:36 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 10:54:39 - logs.config_logger - INFO - pdf_generator.py:169 - Modo TEST activado: Generando PDF vacío.
2024-05-16 10:54:39 - logs.config_logger - DEBUG - pdf_generator.py:152 - Ruta del archivo configurada: C:\AppServ\www\Presupuestador\generated_pdfs\test_20240516_105439.pdf
2024-05-16 10:54:39 - logs.config_logger - INFO - pdf_generator.py:155 - PDF generado exitosamente.
2024-05-16 10:55:02 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 10:55:02 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:01:40 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:01:40 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:03:37 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:03:37 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:04:27 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:04:27 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:13:10 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:13:10 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:16:19 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:16:19 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:18:35 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:18:35 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:19:18 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:19:18 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:20:46 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:20:46 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:26:22 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:26:22 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:31:46 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:31:46 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:36:06 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:36:06 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:37:51 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:54:11 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:54:11 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:55:52 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:55:52 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 11:57:07 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 11:57:07 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 12:00:33 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 12:00:34 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 12:01:58 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 12:01:58 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 12:02:15 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 12:02:15 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 12:02:17 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 12:20:40 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 12:20:40 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 12:20:47 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 12:20:47 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 12:54:01 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 12:54:01 - logs.config_logger - INFO - database.py:30 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 12:55:55 - logs.config_logger - INFO - pdf_generator.py:169 - Modo TEST activado: Generando PDF vacío.
2024-05-16 12:55:55 - logs.config_logger - DEBUG - pdf_generator.py:152 - Ruta del archivo configurada: C:\AppServ\www\Presupuestador\generated_pdfs\test_20240516_125555.pdf
2024-05-16 12:55:55 - logs.config_logger - INFO - pdf_generator.py:155 - PDF generado exitosamente.
2024-05-16 13:03:26 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 13:03:30 - logs.config_logger - ERROR - database.py:49 - Error de base de datos: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2024-05-16 13:03:30 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:03:51 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 13:03:55 - logs.config_logger - ERROR - database.py:49 - Error de base de datos: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2024-05-16 13:03:55 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:06:15 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 13:06:19 - logs.config_logger - ERROR - database.py:49 - Error de base de datos: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2024-05-16 13:06:19 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:07:24 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 13:07:28 - logs.config_logger - ERROR - database.py:49 - Error de base de datos: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2024-05-16 13:07:28 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:18:12 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 13:18:12 - logs.config_logger - ERROR - database.py:46 - Error de programación en SQL: 1049 (42000): Unknown database 'presupuestador_db'
2024-05-16 13:18:12 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:18:15 - logs.config_logger - INFO - pdf_generator.py:169 - Modo TEST activado: Generando PDF vacío.
2024-05-16 13:18:15 - logs.config_logger - DEBUG - pdf_generator.py:152 - Ruta del archivo configurada: C:\AppServ\www\Presupuestador\generated_pdfs\test_20240516_131815.pdf
2024-05-16 13:18:15 - logs.config_logger - INFO - pdf_generator.py:155 - PDF generado exitosamente.
2024-05-16 13:26:33 - logs.config_logger - INFO - pdf_generator.py:169 - Modo TEST activado: Generando PDF vacío.
2024-05-16 13:26:33 - logs.config_logger - DEBUG - pdf_generator.py:152 - Ruta del archivo configurada: C:\AppServ\www\Presupuestador\generated_pdfs\test_20240516_132633.pdf
2024-05-16 13:26:33 - logs.config_logger - INFO - pdf_generator.py:155 - PDF generado exitosamente.
2024-05-16 13:27:15 - logs.config_logger - INFO - main.py:29 - Iniciando la aplicación
2024-05-16 13:27:15 - logs.config_logger - ERROR - database.py:46 - Error de programación en SQL: 1049 (42000): Unknown database 'presupuestador_db'
2024-05-16 13:27:15 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:28:35 - logs.config_logger - INFO - main.py:38 - Iniciando la aplicación
2024-05-16 13:28:35 - logs.config_logger - ERROR - database.py:46 - Error de programación en SQL: 1049 (42000): Unknown database 'presupuestador_db'
2024-05-16 13:28:35 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:30:30 - logs.config_logger - INFO - main.py:33 - Iniciando la aplicación
2024-05-16 13:30:30 - logs.config_logger - ERROR - database.py:46 - Error de programación en SQL: 1049 (42000): Unknown database 'presupuestador_db'
2024-05-16 13:30:30 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:31:10 - logs.config_logger - INFO - main.py:37 - Iniciando la aplicación
2024-05-16 13:31:10 - logs.config_logger - ERROR - database.py:46 - Error de programación en SQL: 1049 (42000): Unknown database 'presupuestador_db'
2024-05-16 13:31:10 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:33:02 - logs.config_logger - INFO - main.py:37 - Iniciando la aplicación
2024-05-16 13:33:02 - logs.config_logger - ERROR - database.py:46 - Error de programación en SQL: 1049 (42000): Unknown database 'presupuestador_db'
2024-05-16 13:33:02 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:33:39 - logs.config_logger - INFO - main.py:37 - Iniciando la aplicación
2024-05-16 13:33:39 - logs.config_logger - ERROR - database.py:46 - Error de programación en SQL: 1049 (42000): Unknown database 'presupuestador_db'
2024-05-16 13:33:39 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:35:25 - logs.config_logger - INFO - main.py:37 - Iniciando la aplicación
2024-05-16 13:35:25 - logs.config_logger - ERROR - database.py:46 - Error de programación en SQL: 1049 (42000): Unknown database 'presupuestador_db'
2024-05-16 13:35:25 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:36:31 - logs.config_logger - INFO - main.py:37 - Iniciando la aplicación
2024-05-16 13:36:32 - logs.config_logger - ERROR - database.py:46 - Error de programación en SQL: 1049 (42000): Unknown database 'presupuestador_db'
2024-05-16 13:36:32 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:36:33 - logs.config_logger - ERROR - main.py:30 - Error: 'NoneType' object has no attribute 'cursor'. Verifique la conexión a la base de datos.
2024-05-16 13:37:34 - logs.config_logger - INFO - main.py:37 - Iniciando la aplicación
2024-05-16 13:37:34 - logs.config_logger - ERROR - database.py:46 - Error de programación en SQL: 1049 (42000): Unknown database 'presupuestador_db'
2024-05-16 13:37:34 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:37:36 - logs.config_logger - ERROR - main.py:30 - Error: 'NoneType' object has no attribute 'cursor'. Verifique la conexión a la base de datos.
2024-05-16 13:38:39 - logs.config_logger - INFO - main.py:37 - Iniciando la aplicación
2024-05-16 13:38:39 - logs.config_logger - ERROR - database.py:46 - Error de programación en SQL: 1049 (42000): Unknown database 'presupuestador_db'
2024-05-16 13:38:39 - logs.config_logger - ERROR - database.py:25 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 13:38:40 - logs.config_logger - ERROR - main.py:30 - Error: 'NoneType' object has no attribute 'cursor'. Verifique la conexión a la base de datos.
2024-05-16 15:04:37 - logs.config_logger - INFO - main.py:37 - Iniciando la aplicación
2024-05-16 15:04:37 - logs.config_logger - ERROR - database.py:43 - Error de programación en SQL: 1049 (42000): Unknown database 'presupuestador_db'
2024-05-16 15:04:37 - logs.config_logger - ERROR - database.py:24 - No fue posible establecer una conexión inicial con la base de datos.
2024-05-16 15:04:39 - logs.config_logger - ERROR - main.py:30 - Error: 'NoneType' object has no attribute 'cursor'. Verifique la conexión a la base de datos.
2024-05-16 15:05:32 - logs.config_logger - INFO - main.py:37 - Iniciando la aplicación
2024-05-16 15:05:32 - logs.config_logger - INFO - database.py:28 - Conectado al servidor MySQL versión 8.0.17
2024-05-16 15:05:32 - logs.config_logger - INFO - database.py:89 - No se encontraron tablas en la base de datos. Creando tablas...
2024-05-16 15:05:32 - logs.config_logger - DEBUG - database.py:96 - Creando tablas en la base de datos
2024-05-16 15:05:32 - logs.config_logger - ERROR - database.py:163 - Error de sintaxis SQL: 1060 (42S21): Duplicate column name 'fecha_presupuesto'
2024-05-16 15:05:34 - logs.config_logger - INFO - main.py:15 - The 'presupuestos' table was not found. Creating tables...
2024-05-16 15:05:34 - logs.config_logger - DEBUG - database.py:96 - Creando tablas en la base de datos
2024-05-16 15:05:34 - logs.config_logger - ERROR - database.py:163 - Error de sintaxis SQL: 1060 (42S21): Duplicate column name 'fecha_presupuesto'
2024-05-16 15:05:34 - logs.config_logger - INFO - main.py:17 - Tables created successfully.
2024-05-23 10:35:01 - logs.config_logger - INFO - main.py:37 - Iniciando la aplicación
2024-05-23 10:35:01 - logs.config_logger - INFO - database.py:28 - Conectado al servidor MySQL versión 8.0.17
2024-05-23 10:35:01 - logs.config_logger - INFO - database.py:89 - No se encontraron tablas en la base de datos. Creando tablas...
2024-05-23 10:35:01 - logs.config_logger - DEBUG - database.py:96 - Creando tablas en la base de datos
2024-05-23 10:35:01 - logs.config_logger - ERROR - database.py:163 - Error de sintaxis SQL: 1060 (42S21): Duplicate column name 'fecha_presupuesto'
2024-05-23 10:35:05 - logs.config_logger - INFO - main.py:15 - The 'presupuestos' table was not found. Creating tables...
2024-05-23 10:35:05 - logs.config_logger - DEBUG - database.py:96 - Creando tablas en la base de datos
2024-05-23 10:35:05 - logs.config_logger - ERROR - database.py:163 - Error de sintaxis SQL: 1060 (42S21): Duplicate column name 'fecha_presupuesto'
2024-05-23 10:35:05 - logs.config_logger - INFO - main.py:17 - Tables created successfully.
2024-05-23 10:35:45 - logs.config_logger - INFO - main.py:37 - Iniciando la aplicación
2024-05-23 10:36:09 - logs.config_logger - INFO - main.py:37 - Iniciando la aplicación
2024-05-23 10:36:09 - logs.config_logger - INFO - database.py:28 - Conectado al servidor MySQL versión 8.0.17
2024-05-23 10:36:09 - logs.config_logger - INFO - database.py:89 - No se encontraron tablas en la base de datos. Creando tablas...
2024-05-23 10:36:09 - logs.config_logger - DEBUG - database.py:96 - Creando tablas en la base de datos
2024-05-23 10:36:09 - logs.config_logger - ERROR - database.py:163 - Error de sintaxis SQL: 1060 (42S21): Duplicate column name 'fecha_presupuesto'
2024-05-23 10:36:49 - src.logs.config_logger - INFO - installer_aux.py:93 - Iniciando instalador
2024-05-23 10:36:49 - src.logs.config_logger - INFO - installer_aux.py:32 - Acceso directo actualizado exitosamente.
2024-05-23 10:42:52 - logs.config_logger - INFO - main.py:37 - Iniciando la aplicación
2024-05-23 10:42:52 - logs.config_logger - INFO - database.py:28 - Conectado al servidor MySQL versión 8.0.17
2024-05-23 10:42:52 - logs.config_logger - INFO - database.py:89 - No se encontraron tablas en la base de datos. Creando tablas...
2024-05-23 10:42:52 - logs.config_logger - DEBUG - database.py:96 - Creando tablas en la base de datos
2024-05-23 10:42:52 - logs.config_logger - ERROR - database.py:163 - Error de sintaxis SQL: 1060 (42S21): Duplicate column name 'fecha_presupuesto'
2024-05-23 10:42:55 - logs.config_logger - INFO - main.py:15 - The 'presupuestos' table was not found. Creating tables...
2024-05-23 10:42:55 - logs.config_logger - DEBUG - database.py:96 - Creando tablas en la base de datos
2024-05-23 10:42:55 - logs.config_logger - ERROR - database.py:163 - Error de sintaxis SQL: 1060 (42S21): Duplicate column name 'fecha_presupuesto'
2024-05-23 10:42:55 - logs.config_logger - INFO - main.py:17 - Tables created successfully.
